amcl:
  ros__parameters:
    use_sim_time: True
    # --- AJUSTE DE ESTABILIDADE ---
    # Voltamos alpha para 0.1 (0.2 foi muito agressivo e fez o robô sair do mapa)
    alpha1: 0.1
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.1
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    tf_broadcast: true
    transform_tolerance: 1.0 # Reduzido para exigir sincronia melhor
    
    # --- CORREÇÃO VISUAL SEM PESAR A CPU ---
    # Partículas voltam ao normal para não travar o PC
    min_particles: 500
    max_particles: 2000
    # O SEGREDO: Atualizar mais vezes (a cada 10cm ou 0.1 radianos)
    # Isso deixa o movimento no Rviz "liso" sem perder a localização
    update_min_d: 0.10
    update_min_a: 0.10

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 30 # Aumentado de 10 para 30 dica ia
    default_server_timeout: 20
    transform_tolerance: 1.0

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 6.0 # Aumentado para 10Hz para resposta mais rápida
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 5.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] 
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 60.0
    
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.90     # tolarancia na distância na chegada
      yaw_goal_tolerance: 1.20    # toleancia de ângulo na chegada
    
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.26
      lookahead_dist: 1.0    # Quão longe ele olha para frente (aumente se ele tremer)
      min_lookahead_dist: 0.6  # Mínimo aceitável
      max_lookahead_dist: 2.0  # Máximo
      lookahead_time: 2.0  # Olha 2 segundos no futuro
      rotate_to_heading_min_angle: 1.57 # valor testado: 0.785 Isso diz: "Só pare para girar se a curva for muito fechada (>45 graus). Se for curva suave, vá direto."
      transform_tolerance: 1.5
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 1.0
      use_collision_detection: false
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      allow_reversing: false   # Mude para true se quiser que ele dê ré
      rotate_to_heading_vel: 0.4
      max_angular_accel: 0.5
      max_robot_pose_search_dist: 10.0
      cost_scaling_dist: 0.3
      cost_scaling_gain: 1.0
      inflation_cost_scaling_factor: 3.0
      
      # Mantendo o comportamento de girar antes de andar (que estava bom)
      angular_dist_threshold: 0.785
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 0.3  #Se o alvo estiver torto mais que 11 graus, ele PARA e gira.
      max_angular_accel: 0.5
      simulate_ahead_time: 1.0

      
local_costmap:
  local_costmap:
    ros__parameters:
      transform_tolerance: 1.5
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: True
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      footprint: "[[-1.01, -1.04], [-1.01, 1.04], [1.01, 1.04], [1.01, -1.04]]"
      
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.2
        z_voxels: 13          # <--- AQUI: 25 * 0.1 = 2.5 metros de altura (cobre seu lidar de 1.66m)
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0    # sensor do robo de distancia
        inflation_radius: 1.03

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: True
      transform_tolerance: 1.5
      resolution: 0.09
      track_unknown_space: true
      footprint: "[ [0.76, 0.87], [0.76, -0.87], [-0.76, -0.87], [-0.76, 0.87] ]"
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.03
      always_send_full_costmap: False

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "meu_mapa.yaml"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 0.001  # frequancia que se calcula a rota
    planner_plugins: ["GridBased"]
    GridBased:
      # O NOME CORRETO É ESTE ABAIXO:
      plugin: "nav2_navfn_planner/NavfnPlanner"   # Mude de "nav2_smac_planner/SmacPlannerHybrid"
      downsampling_factor: 1
      tolerance: 0.5
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      minimum_turning_radius: 0.00  # Ajuste conforme o quanto seu robô consegue virar
      motion_model_for_search: "DUBIN" # ou "REEDS_SHEPP" se ele puder dar ré
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5

velocity_smoother:
  ros__parameters:
    use_sim_time: True
    smoothing_frequency: 6.0 # de 10 para 6 ia
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.10, 0.0, 0.7] 
    min_velocity: [-0.26, 0.0, -0.7]
    max_accel: [0.01, 0.0, 1.0]
    max_decel: [-1.5, 0.0, -1.5]
    odom_topic: "odom"
    robot_base_frame: "base_footprint"

collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_nav"    # O Nav2 envia para cá
    cmd_vel_out_topic: "cmd_vel"       # O Monitor limpa e envia para o Sabertooth
    state_topic: "collision_monitor_state"
    transform_tolerance: 1.0
    source_timeout: 2.0
    base_shift_correction: True
    stop_pub_timeout: 1.0

    # Fontes de dados (seu Lidar)
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"

    # --- ZONAS DE SEGURANÇA ---
    polygons: ["Positivo_Stop", "Positivo_Slowdown"]

    # Zona 1: PARADA CRÍTICA (Seu pedido de 10cm)
    # Medidas: Robô (1.50x1.73). Adicionamos 0.10m em cada lado.
    Positivo_Stop:
      type: "polygon"
      points: "[[-1.06, -1.19], [-1.06, 1.19], [1.06, 1.19], [1.06, -1.19]]"
      action_type: "stop"
      min_points: 3
      visualize: True

    # Zona 2: REDUÇÃO DE VELOCIDADE (Para não dar tranco no Sabertooth)
    # Medidas: 30cm de folga ao redor
    Positivo_Slowdown:
      type: "polygon"
      points: "[[-1.05, -1.165], [-1.05, 1.165], [1.05, 1.165], [1.05, -1.165]]"
      action_type: "slowdown"
      slowdown_ratio: 0.3
      min_points: 3
      visualize: True

waypoint_follower:
  ros__parameters:
    use_sim_time: True
    loop_rate: 20
    stop_on_failure: True  # SEGURANÇA: Se errar um ponto, para tudo.
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 2 # 20000ms = 20 Segundos de espera (Inspeção)
